# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main

pool:
  name: AgentPool

variables:
  - group: GitHubSecrets

steps:
  - script: |
      git clone https://$(github_username):$(github_token)@github.com/swarnasurendar1626/example.git
      cd example
      echo "✅ Repo cloned successfully!"
    displayName: 'Clone External GitHub Repository'

  - task: Maven@3
    inputs:
      mavenPomFile: 'example/pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'